services:
  - type: web
    name: solar-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn solar_dashboard:app.server --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
